### ISSUE TITLE
Data detallada

### ISSUE THREAD

**Issue by sergiocorreia** [jmcastagnetto/2021-segunda-vuelta-eleccion-presidencial-peru#1]
En caso sea util:

Data por acta: https://docs.google.com/spreadsheets/d/1PevjP88hNI9_ypKuROGa1zzJHENGM0kgjuQYDTcPZ8M/edit?usp=sharing

(El scrapper esta en Python, lo puedo adjuntar tambien)

**Comment by jmcastagnetto** [comment]
:+1: Con tu permiso, puedo poner el link y/o una versión en CSV en este repo, si no tienes problema con ello.

**Comment by sergiocorreia** [comment]
No es necesario el crédito, y claro que si. Voy a actualizar el link conforme haya mas data. Tambien hay un par de columnas extra (URL con el imagen del acta, direccion del local) que no inclui por espacio, pero podrian ser util.

**Comment by jmcastagnetto** [comment]
OK, voy a hacer un script para tener el CSV un par de veces al día. Y de todas maneras te pongo como fuente, es buena práctica y alienta la colaboración. :-)

**Comment by jmcastagnetto** [comment]
Ya he puesto el script, y he añadido el CSV. Sólo un par de cambios menores: poner el UBIGEO en formato con 6 digitos, y cambiar los nombres de los campos de votos por los partidos ("votos_perulibre" y "votos_fuerzapopular" respectivamente). Cuando pongas otros campos, iré ajustando el script.
